# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


language: python
python:
  - "3.6"

env:
  - PIO_ENV=openevse
  - PIO_ENV=openevse_1-6-14
  - PIO_ENV=openevse_1-6-17
  - PIO_ENV=openevse_1-6-23

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - pio upgrade
  - pio --version

script:
  - platformio run -e $PIO_ENV

after_script:
  - grep version= ~/.platformio/packages/framework-arduinoavr/platform.txt
  - ~/.platformio/packages/toolchain-atmelavr/bin/avr-gcc --version
  - ls -l .pio/build/$PIO_ENV/firmware.hex